### ISSUE TITLE
missing config setting for mnist data

### ISSUE THREAD

**Issue by z1w** [columbia/Metric_Learning_Adversarial_Robustness#2]
I am trying to run train_update_fast_triplet.py and train_at_madry.py, but it seems that there are some hyperparameters missing. 

"config_mnist.json" has no "margin_mul", which is needed for "train_update_fast_triplet.py"; and "step_size_schedule_adam" is also missing and needed for "train_at_madry.py". What are the appropriate values for those parameters?

**Comment by ChengzhiCU** [comment]
Thank you for pointing this out. The "margin_mul" for MNIST is 1. "margin_mul" is for applying a different margin to different layers. Our paper uses only one layer thus set it to 1, i.e., it is not useful here. "step_size_schedule_adam" is removed. We here use the SGD schedule the same as Madry et. al.

**Comment by z1w** [comment]
> Thank you for pointing this out. The "margin_mul" for MNIST is 1. "margin_mul" is for applying a different margin to different layers. Our paper uses only one layer thus set it to 1, i.e., it is not useful here. "step_size_schedule_adam" is removed. We here use the SGD schedule the same as Madry et. al.

Hi, I saw there were some updates in the source code, where "mul_num" were deleted; however, it was still used in "train_update_fast_triplet.py". Other than that, I think the issue could be closed. Thanks!

**Comment by ChengzhiCU** [comment]
"mul_num" makes the size of the negative mini-batch "mul_num" times of the training batches. It is 1 for MNIST. Updated the config_mnist.json.
