### ISSUE TITLE
how to prepare imagenet data

### ISSUE THREAD

**Issue by z1w** [columbia/Metric_Learning_Adversarial_Robustness#3]
I tried to prepare imagenet data similar to mnist. I ran "save_imagenet.py" in "utils_folder", but it did not work. 

I took a look at the code. The script builds an empty data_folder first, and then immediately tried to read "word.txt" from the folder. What should be the right way to prepare the imagenet data?

**Comment by ChengzhiCU** [comment]
Download the Tiny-imagenet data to folder imagenet_data first, then run the  "save_imagenet.py" in "utils_folder". The script builds an empty data_folder is unnecessary. Thanks for pointing this out. Let me know if this helps.

**Comment by z1w** [comment]
> Download the Tiny-imagenet data to folder imagenet_data first, then run the "save_imagenet.py" in "utils_folder". The script builds an empty data_folder is unnecessary. Thanks for pointing this out. Let me know if this helps.

Thanks for the prompt reply. Yes, I tried that and that works!
