### ISSUE TITLE
Cifar10 Negative sample

### ISSUE THREAD

**Issue by say2sarwar** [columbia/Metric_Learning_Adversarial_Robustness#4]
Thank you so much for your code. 

i am using ResNet20 for CIFAR10. what should be the negative samples? did you any experience with that. 

Thank you for your time.

**Comment by ChengzhiCU** [comment]
I never tried that. Given ResNet20 is a much smaller model than our studied WRN, I believe the negative samples should be easier ones. A large model capacity is needed to separate hard negatives. One concern is that easy negative may yield inferior robustness.

**Comment by say2sarwar** [comment]
Thank you so much.
