### ISSUE TITLE
Cifar10 Performance using TLA

### ISSUE THREAD

**Issue by say2sarwar** [columbia/Metric_Learning_Adversarial_Robustness#5]
Thank you for sharing the code. 

what is the setting you used for cifar10? i run the code multiple times, but unable to get the results. what model? epsilon value? step size ? etc

Thank you in advance for your help.

**Comment by ChengzhiCU** [comment]
Can you clarify how you run it? What are the detailed results you get? It can help to troubleshoot. For cifar10, it's the same WRN model as Madry et. al. , eps=8, stepsize=2. You should be able to get an evaluation curve like tfboard.png.

**Comment by say2sarwar** [comment]
i am using Resnet50 model in your code with eps=8 stepsize=2. using A_AP_B AND A1_AP_B are true. the reset of the setting are same as config_cifar.json. I haven't change anything. i am getting 43.5% on pgd 20 while using diff_neg. the results are almost the same for default negative selection.

if you any more questions, please let me know.

**Comment by say2sarwar** [comment]
![image](https://user-images.githubusercontent.com/34134990/81705626-d0af0d00-94a1-11ea-826f-ff097dbe03cf.png)

**Comment by ChengzhiCU** [comment]
The reason is that you should use WRN (default, the same as Madry et. al.) instead of Res50. If you just want to test Res50, you probably need smaller lambda and margin, since it is a smaller model. I didn't try Res50. The paper reports WRN result.

**Comment by say2sarwar** [comment]
Thank you so much for clarification. i can't find the WRN network in your code. did you include WRN model in your code? 

Thank yo again for the clarification. really appreciate it.

**Comment by ChengzhiCU** [comment]
You are welcome! It's https://github.com/columbia/Metric_Learning_Adversarial_Robustness/blob/028ec1d21030fb0eb81b30088e7a1896aacd1645/train_update_fast_triplet.py#L197 . Sorry for the confusion we should've given it `WRN' name.

**Comment by say2sarwar** [comment]
Thank you so much.
